### ISSUE TITLE
Level editor

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#1]
## Description
A level editor would be useful for creating levels easier, but also for a more intricate level design, which would not be possible in a Tiled environment, where every map object is a square tile. 

An example of the current limitations is that you can't place a platform at an angle, nor can the platforms can be a different width to the map's tile size, which in this case is 64px.

## Tasks
- [x] Design and add a button which takes the player to the level editor screen
- [x] Add a grid made out of 64px squares
- [x] Add support for gestures:
  - [x] Panning
  - [x] Zooming
- [x] Add an object placement button
- [x] Add support for selecting map objects when tapped
- [x] Add an overlay to the selected map object which contains buttons for:
  - [x] Resizing the object
  - [x] Rotating the object
  - [x] Moving the object
  - [x] Deleting the object
- [x] Add undo/redo buttons (#2)
- [x] Add a player object (#4)
- [x] Add a finish object (#6)
- [x] Make the edited levels playable (#3)
- [x] Add support for saving edited levels to a file and loading them back (#12)
- [x] Fix compatibility issues caused by the new map file type (#7)
- [x] Add UI for saving/loading levels (#13)
- [x] Improve the map rendering system to make the objects have rounded corners (#17)
