### ISSUE TITLE
Better movement of rotated objects

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#11]
## Description
Currently, if the player wants to move a rotating platform in the level editor, it is, in some cases, rather hard. The problem can be seen in the following image:

![rect904](https://user-images.githubusercontent.com/44314433/53427948-89e70b80-39f2-11e9-92f9-a3039c4d26e5.png)

In green are the current directions you can move a map object. In red are the ways the movement of rotated objects could improve.

## Idea
DO keep the current way rotated objects move because it too is useful in some cases. Rather, change the direction the object moves when the player taps (or holds) on a movement button.

 By that, I mean that if the player tapped on the vertical movement button here:

![rect951-3-6-7-0](https://user-images.githubusercontent.com/44314433/53429636-b3edfd00-39f5-11e9-9a38-40ae1f6f7808.png)

Then the button would become:

![rect951-3-6-7-0-2](https://user-images.githubusercontent.com/44314433/53429675-c36d4600-39f5-11e9-930f-7e23dd47e4ea.png)

And it would let the player move the platform in a previously unsupported way. The same for the horizontal movement button.

This would work because you don't usually tap on the movement buttons, but rather you drag them.

## Tasks
- [x] Change the button's icon angle at double-tap
- [x] Change how the button works when rotation is taken into account
- [ ] Disable snapping for movement where rotation is taken into account
