### ISSUE TITLE
Save/load functionality

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#12]
## Description
The player should be able to save the maps he creates in the level editor, but also load them back. 

## Tasks
- [x] Define how a maps file would look like
- [x] Add save to JSON functionality
- [x] Fix the id of map objects to be unique, and not 0
- [x] Add load from JSON functionality
