### ISSUE TITLE
Save/load UI

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#13]
## Description
The player should be able to save the levels made in the level editor. However, currently levels can be saved only on the Desktop version, by pressing `S`.

## Tasks
- [x] Add a settings button to the level editor
- [x] Add a pop up menu which appears when the settings button is pressed
- [x] Save the map (with the correct name and id) when the save button is pressed
- [x] Add a pop up that appears when you save a level (e.g. "Level saved.")
- [x] Add a pop up which appears when the "Load" button is pressed
- [x] Show when a level was last edited
- [x] Add a pop-up for confirming loading or deleting a level
- [x] Add loading edited levels functionality
