### ISSUE TITLE
Distance field fonts

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#14]
## Description
Currently, the game has 6 fonts, 4 of them being just differently sized bold fonts. And this number will only rise, as I add more fonts (e.g. `light`, `semi-bold`, `extra-bold`) of different sizes (each font size requires a new `.fnt` and `.png` file). 

[Distance field fonts](https://github.com/libgdx/libgdx/wiki/Distance-field-fonts) would allow to have only a size of each font type, as resizing won't make them pixelated. However, there may be a performance hit, as the technique uses shaders. 

The [implementation](https://stackoverflow.com/a/36525940/10081700) I currently have in mind would cause an expensive batch flush for every `Label` drawn. And I really doubt that there would be a better implementation using `Scene2D`. 

But it is not like there will be 1000 `Labels` on the screen at once (maybe 30 at most?), so I doubt that the performance should be such a big concern.

## Tasks
- [x] Generate distance field fonts for every font type
- [x] Create `LabelStyles` for every font type
- [x] Create my own `DistanceFieldLabel` class
- [x] Replace every text in the game to use distance field fonts
- [x] Remove old fonts
