### ISSUE TITLE
Remove map size

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#16]
## Description
Currently, every map has a width and a height. However, they are not at all necessary.

Since the map is not made out of tiles (e.g. 64x64 tiles), but out of objects (e.g. an object at x=30, y=45), the map size is more of a self-imposed limitation. 

Also, a smaller map doesn't result in less memory used, because the map is not stored as a matrix (of tiles), but as an array (of objects).

The only place where the map size is used is in the system which makes the camera follow the player, so the camera is kept within the bounds of the map.

The idea is then to use the position of the leftmost, rightmost, bottom-most and topmost map object to keep the camera within bounds, which would be the only use case of the map size.

## Tasks
- [x] Remove the `Resize` button from the level editor
- [x] Add `mapLeft`, `mapRight`, `mapTop` and `mapBottom` and a function to update them
- [x] Update the map bounds where necessary (adding platforms, moving platforms, etc.)
- [x] Remove the usage of `mapWidth` and `mapHeight` and replace it with map bounds
