### ISSUE TITLE
Rounded platforms

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#17]
## Description
Currently, platforms are just rectangles, with hard edges, but they don't fit the general style of the game, which is more rounded. 

## Tasks
- [x] Create 16 platform textures with each of the 4 corners being either rounded or straight
- [x] Add support for [nine patches](https://github.com/libgdx/libgdx/wiki/Ninepatches)
- [x] Use [bitmasking](https://gamedevelopment.tutsplus.com/tutorials/how-to-use-tile-bitmasking-to-auto-tile-your-level-layouts--cms-25673) to set the correct texture
- [x] Update the rounded corners at the correct times (e.g. in the level editor, when resizing a platform)
