### ISSUE TITLE
Undo/Redo functionality

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#2]
## Description
The player should be able to undo/redo changes made in the level editor.

## Tasks
- [x] Make undo/redo handle the following actions:
  - [x] Adding objects
  - [x] Repositioning objects
  - [x] Resizing objects
  - [x] Rotating objects
  - [x] Deleting objects
- [x] Make the undo/redo buttons work: 
  - [x] When tapped, they should undo/redo
  - [x] If there is nothing to undo/redo, the buttons should be grayed out
