### ISSUE TITLE
Level editor save pop-up

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#22]
## Description
When the player leaves the level editor, he should be asked whether he wants to save the level, in case it is a new level. 

So if the player loaded a level and edited it, the level should be saved automatically. Only if it is a new level should the player be asked.

## Tasks
- [x] Add pop-up that asks the player if he is sure he wants to leave the level editor
- [x] Add pop-up that asks the player if he wants to save the (new) level, in case he pressed yes at the previous pop-up
- [x] Save the map accordingly
- [x] Modify the save code not to modify the file (thus the last edited time) in case the content of the new JSON is the same as the file's (so leaving the level editor doesn't modify last edited time wrongfully)
