### ISSUE TITLE
Camera padding settings

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#24]
## Description
In the game, the camera follows the player around, within the map bounds. However, the editor may want the camera to follow the player a bit outside the bounds too, which would be the padding. 

So, in the level editor you should be able to set the camera's left, right, top and bottom padding.

## Tasks
- [x] Add the button itself
- [x] Design the widget
- [x] Implement the design
- [x] Add padding functionality
- [x] Add padding values to map files
