### ISSUE TITLE
Make edited levels playable

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#3]
## Description
The user should be able to also play the level he is editing in order to test it.

## Tasks
- [x] Add a play button in the level editor
- [x] Add a back button which takes you back to the level editor
- [x] Create Box2D bodies from the placed map objects
- [x] Make the player be affected by physics
- [x] Reset the player's position when the back button is pressed
- [x] Add shooting ability to the player
- [x] Restart the level when the player is off-screen
- [x] Make the camera follow the player
- [x] Keep the camera within the map's bounds
- [x] Automatically add a platform in the level editor
- [x] Restart the level when the player enters the finish point
