### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#30]
## Description
Lately, the JVM garbage collector gets called quite a lot, which means that resources are wasted or leaked. And this obviously isn't a good thing, as it results in lag spikes every now and then.

## Tasks
- [x] Use object pooling where necessary
- [x] Reduce calls to memory intensive functions
- [x] Remove useless initializations
