### ISSUE TITLE
Collectible points

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#31]
## Description
If a map contained a collectible point, then the player couldn't just go in the finish point and win, but it would have to collect the point, in order for the finish point to "open".

## Tasks
- [x] Design the collectible point
- [x] Add support for placing collectible points in the level editor
- [x] Add support for collecting points
- [x] Re-add points back after restarting the level
- [x] Add support for loading and saving maps with collectible points
- [x] Make the finish point inaccessible if not every point was collected
