### ISSUE TITLE
Moving platforms

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#32]
## Description
Something that could be interesting would be moving platforms, either up and down, side to side, or diagonally. 

## Tasks
- [x] Design how a moving platform would look in the level editor
- [x] Add support for placing moving platforms in the level editor
- [x] Link actions made to platforms (resizing & rotating) with the entity which holds the target position
- [x] Make the moving platform actually move back and forth
- [x] Update the platforms' overlay so you can make a platform both moving and destroyable
- [x] Add dashed line between moving platforms and their target position
- [x] Add support for saving maps that have moving platforms
