### ISSUE TITLE
Rotating platforms

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#33]
## Description
Rotating platforms may be pretty interesting as well, so I could implement them. 

While I doubt that they could be used as ground that easily (so the player would have to stay and jump from it), they could be used as obstacles, pushing the player off the platforms.

## Tasks
- [x] Design how a rotating platform would look in the level editor
- [x] Implement the rotating platforms themselves, so they work
- [x] Add support for saving levels that have rotating platforms
