### ISSUE TITLE
Destroyable platforms

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#34]
## Description
An element that could make for some intelligent level design would be destroyable platforms. So if the player shot them, they would disappear.

The reason they could be interesting is that they could make the players think if they want to "burn bridges" by destroying a platform, which would make them more careful, and thinking more in the future.

## Tasks
- [x] Design how a destroyable platform would look like 
- [x] Add UI support for selecting a destroyable platform in the level editor
- [x] Add support for placing a one tile destroyable platform
- [x] Refactor code to use `Scene2DComponent` instead of `ImageComponent`
- [x] Make the level editor fully compatible
- [x] Create destroyable Box2D body from the Scene2D
- [x] Add support for saving levels that have destroyable platforms
