### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#37]
## Description
Every level should have a leaderboard, which would take into account the number of moves a level was finished in.

This is a replacement for the previous star system, as the game seems, from what I've seen, pretty hard, and having to finish a level in a fixed number of steps would just drive players away from anger, I think.

This would also solve the problem of people complaining that there is no limit on how many times you can shot, without actually restricting the player from such a playstyle, but rather offering an alternative (to get rank 1 on every level, for example).

It would also increase replayability (which is non-existent, currently).

## Tasks
- [x] Add a Firebase Realtime Database
- [x] Start collecting data, so the leaderboard is already populated when adding the UI
- [x] Display the rank based on the number of shots at the bottom of the screen
- [x] Add a screen between levels giving the player the chance to play the level again
- [x] Show the rank under the level label in the level selector
- [x] Add a pane showing the level's entire leaderboard when a button is pressed
