### ISSUE TITLE
Add a player object in the level editor

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#4]
## Description
In the level editor there should be a player object added automatically for every map. It would indicate the spawn point of the player. It should also be unremovable, because there can't be a level without a player. 

## Tasks
- [x] Automatically add a player object for every map
- [x] Remove irrelevant buttons from the player's overlay (resizing and deletion)
- [x] Adapt the overlay to be correctly spaced for the player object's size
