### ISSUE TITLE
Rate game prompt

### ISSUE THREAD

**Issue by Luca1152** [Luca1152/gravity-box#44]
## Description
The player should be prompted to rate the game after finishing the 4th or so level, as I read somewhere that it (clearly) increases the number of rates and reviews **dramatically**, thus boosting the game's search rank.

## Tasks
- [x] Create the prompt pop-up
- [x] Prompt user after finishing the 3rd level
- [x] If the user pressed "Maybe later", prompt the user after finishing the 6th level
